# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://wkrzywiec.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 100

[outputs]
  home = ["HTML", "RSS", "JSON"]
